inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Metrics/LineLength:
  Max: 120

RSpec/DescribeClass:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false
