# configuration settings for bibframe validation
helper_method: marc_to_graph_m2bf_xquery

# Settings for marc2bibframe LoC xquery converter
#   see spec/support/m2bf_xquery_helpers.rb
# location of clone repo from git@github.com:lcnetdev/marc2bibframe.git
marc2bibframe_path: /path/to/marc2bibframe
# location of saxon jar
saxon_jar_path: /path/to/saxon.jar
# base URI to use for fake urls created
base_uri: http://example.org/
